all:	alarmClock clock ex2

ex2: ex2.c
	gcc -Wall -o ex2 ex2.c

alarmClock: alarmClock.c
	gcc -Wall -o alarmClock alarmClock.c

clock:	clock.c
	gcc -Wall -o clock clock.c

clean:	
	rm -f alarmClock clock ex2

